apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: openshift-monitoring
  namespace: {{ grafana_instance_namespace }}
spec:
  name: openshift-monitoring.yaml
  datasources:
  - name: OpenShift Monitoring
    type: prometheus
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      timeInterval: 5s
      tlsSkipVerify: true
    secureJsonData:
      httpHeaderValue1: Bearer {{ grafana_serviceaccount_jwt.stdout }}
    url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
