- name: Grab grafana service account token
  command: oc serviceaccounts get-token --namespace {{ grafana_instance_namespace }} {{ grafana_instance_name }}-serviceaccount
  changed_when: False
  register: grafana_serviceaccount_jwt

- name: Remove Grafana configuration for OpenShift monitoring metrics
  k8s:
    definition: "{{ lookup('template', item) }}"
    state: absent
  loop:
    - metrics/grafana-cluster-monitoring-view-clusterrolebinding.yaml
    - metrics/openshift-monitoring-grafanadatasource.yaml

- name: Delete Grafana instance
  command: oc delete --kustomize {{ grafana_kustomizations.instance }}

- name: Obtain CSV name
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: '{{ grafana_subscription_name }}'
    namespace: '{{ grafana_subscription_namespace }}'
  register: operator_subscription

- name: Delete Grafana operator
  command: oc delete --kustomize {{ grafana_kustomizations.operator }}

- name: Clean up CSVs
  include_role:
    name: common
    tasks_from: delete_csvs.yml
  vars:
    delete_csvs_name: '{{ operator_subscription.resources.0.status.currentCSV }}'