- hosts: localhost
  gather_facts: False
  tasks:
    - import_role:
        name: common
        tasks_from: enable_user_monitoring.yml
    - import_role:
        name: distributed-tracing-platform
        tasks_from: deploy.yml
    - import_role:
        name: elasticsearch_operator
        tasks_from: deploy.yml
    - import_role:
        name: grafana
        tasks_from: deploy.yml