- name: Waiting since {{ lookup("pipe", "date +%r") }} for {{ operator_name }} operator subscription to appear
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: '{{ subscription_name }}'
    namespace: '{{ subscription_namespace }}'
  register: operator_subscription
  until:
    - operator_subscription.resources.0.status is defined
    - operator_subscription.resources.0.status.currentCSV is defined
  retries: 20
  delay: 10

- name: Print the CSV name
  ansible.builtin.debug:
    msg: Operator subscription {{ operator_subscription }}
  when: debug_enabled == 'true' and operator_subscription is defined

- name: Waiting since {{ lookup("pipe", "date +%r") }} for the {{ operator_name }} operator to deploy
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    name: '{{ operator_subscription.resources.0.status.currentCSV }}'
    namespace: '{{ subscription_namespace }}'
  register: operator_csv
  until:
    - operator_csv.resources.0.status is defined
    - operator_csv.resources.0.status.phase is defined
    - operator_csv.resources.0.status.phase == 'Succeeded'
  retries: 30
  delay: 10

- name: Print the CSV name
  ansible.builtin.debug:
    msg: Operator csv {{ operator_csv }}
  when: debug_enabled == 'true' and operator_csv is defined